title: Social Media Sales Performance Analysis
logo: MetaAds_Analysis.JPG
description: This is a Meta Ad Performance Dashboard that tracks the effectiveness of ad campaigns across key KPIs such as impressions, clicks, engagements, conversions, and budget. 
#show_downloads: true
#google_analytics:
aux_links:
  "Interact with Dashboard here":
    - "https://github.com/ojoepitah/sql-sales-analysis"
theme: jekyll-theme-minimal
